### PR TITLE
Manually copy brotli common lib, workaround for macdeployqt bug.

### PR DESCRIPTION
**Pull request by joeldenning**
https://bugreports.qt.io/browse/QTBUG-100686?focusedCommentId=683436&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-683436

### CODE REVIEW

**Comment by loganmc10** [comment]
The Linux build is failing because it's failing the shellcheck test (bash formatting)

You can test it locally by doing this:
```
shellcheck -o all link-mac.sh
```

https://formulae.brew.sh/formula/shellcheck

**Comment by joeldenning** [comment]
Is the brew update needed?

**Comment by loganmc10** [comment]
Well both the linux and windows builds ship with the latest dependencies.

For example, simple64 uses sdl2 for input, and updates to sdl2 often bring support for new controllers, so it seems like a good idea to keep that sort of thing up to date as possible.

**Comment by joeldenning** [comment]
Unfortunately this isn't working for me. I'll work on getting my local build going so I can properly test it before committing further.

**Pull request closed without merging**
